# 陣列 (Array)

陣列的介紹包含了一維到多維陣列，通常一維陣列也稱為向量 (vector)，二維陣列稱為矩陣 (matrix)。有關於陣列相關的父型別，最主要是由 `AbstractArray`、`AbstractVector`、`AbstractMatrix` 組成，分別可以用來代表 N 維、一維、二維的陣列的抽象型別。


[註1] 在多維陣列提到索引或元素的位置時，我們將採用”直”行(column) ”橫”列(row) 來表示。

[註2] 型別系統將會在後續的內容中進行詳細介紹。

In [3]:
function subtypetree(t, level=1, indent=4)
   level == 1 && println(t)
   for s in subtypes(t)
     println(join(fill(" ", level * indent)) * string(s))
     subtypetree(s, level+1, indent)
   end
end
println(supertype(AbstractArray))
subtypetree(AbstractArray)

Any
AbstractArray
    AbstractRange
        LinRange
        OrdinalRange
            AbstractUnitRange
                Base.IdentityUnitRange
                Base.OneTo
                Base.Slice
                UnitRange
            StepRange
        StepRangeLen
    Base.LogicalIndex
    Base.ReinterpretArray
    Base.ReshapedArray
    BitArray
    CartesianIndices
    Core.Compiler.AbstractRange
        Core.Compiler.LinRange
        Core.Compiler.OrdinalRange
            Core.Compiler.AbstractUnitRange
                Core.Compiler.IdentityUnitRange
                Core.Compiler.OneTo
                Core.Compiler.Slice
                Core.Compiler.StmtRange
                Core.Compiler.UnitRange
            Core.Compiler.StepRange
        Core.Compiler.StepRangeLen
    Core.Compiler.BitArray
    Core.Compiler.LinearIndices
    DenseArray
        Array
        Base.CodeUnits
        Base.Experimental.Const
        Random.UnsafeView
        SharedArrays.SharedArray
        SuiteS

In [4]:
println(supertype(AbstractVector))
subtypetree(AbstractVector)

Any
AbstractArray{T,1} where T
    AbstractRange
        LinRange
        OrdinalRange
            AbstractUnitRange
                Base.IdentityUnitRange
                Base.OneTo
                Base.Slice
                UnitRange
            StepRange
        StepRangeLen
    Base.LogicalIndex
    Base.ReshapedArray{T,1,P,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where P<:AbstractArray where T
    BitArray{1}
    CartesianIndices{1,R} where R<:Tuple{AbstractUnitRange{Int64}}
    Core.Compiler.AbstractRange
        Core.Compiler.LinRange
        Core.Compiler.OrdinalRange
            Core.Compiler.AbstractUnitRange
                Core.Compiler.IdentityUnitRange
                Core.Compiler.OneTo
                Core.Compiler.Slice
                Core.Compiler.StmtRange
                Core.Compiler.UnitRange
            Core.Compiler.StepRange
        Core.Compiler.StepRangeLen
    Core.Compiler.BitArray{1}
    Core.Co

In [5]:
println(supertype(AbstractMatrix))
subtypetree(AbstractMatrix)

Any
AbstractArray{T,2} where T
    Base.ReshapedArray{T,2,P,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where P<:AbstractArray where T
    BitArray{2}
    CartesianIndices{2,R} where R<:Tuple{AbstractUnitRange{Int64},AbstractUnitRange{Int64}}
    Core.Compiler.BitArray{2}
    Core.Compiler.LinearIndices{2,R} where R<:Tuple{Core.Compiler.AbstractUnitRange{Int64},Core.Compiler.AbstractUnitRange{Int64}}
    DenseArray{T,2} where T
        Array{T,2} where T
        Base.Experimental.Const{T,2} where T
        SharedArrays.SharedArray{T,2} where T
        SuiteSparse.CHOLMOD.Dense
    LinearAlgebra.AbstractQ
        LinearAlgebra.HessenbergQ
        LinearAlgebra.QRCompactWYQ
        LinearAlgebra.QRPackedQ
        SuiteSparse.SPQR.QRSparseQ
    LinearAlgebra.AbstractTriangular
        LinearAlgebra.LowerTriangular
        LinearAlgebra.UnitLowerTriangular
        LinearAlgebra.UnitUpperTriangular
        LinearAlgebra.UpperTriangul

## 1. 陣列的建立

最簡單的 array 創建方式，用中括號 `[ ]` 包含所有陣列元素 (element)。

In [40]:
# 以空白分隔進行水平方向的連接
A = [1 5 3]

1×3 Array{Int64,2}:
 1  5  3

In [44]:
A = [1:2 3:4]

2×2 Array{Int64,2}:
 1  3
 2  4

陣列中的元素可以具備不同的資料型別值。可以讓 Julia 自動識別元素類型而不指定，而 Julia 回傳的型別則會是 `Any`。

In [7]:
A = [1.0 "a string" 3]

1×3 Array{Any,2}:
 1.0  "a string"  3

直接指定型別 

In [23]:
A = Rational[0.5 0.3 5.6]

1×3 Array{Rational,2}:
 1//2  5404319552844595//18014398509481984  3152519739159347//562949953421312

使用 `fill()` 函式也可以產生陣列。下例是產生一個 2 x 3 的陣列，陣列內的值均為數字 1。

In [34]:
fill(1, (2, 3))

2×3 Array{Int64,2}:
 1  1  1
 1  1  1

若是要值填入一個既有的陣列，可以使用 `fill!()` 函式。

In [35]:
a = zeros(2, 3)

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [36]:
fill!(a, 3)

2×3 Array{Float64,2}:
 3.0  3.0  3.0
 3.0  3.0  3.0

**(!!) warning**

In [2]:
a = fill!(Vector(undef, 2), 1)

2-element Array{Any,1}:
 1
 1

In [3]:
b = [1; 1]

2-element Array{Int64,1}:
 1
 1

In [4]:
isequal(a, b)

true

In [14]:
fill([1 1], size(a))  # size跟a一樣，但型別從Any改變成Array{Int64,2}

2-element Array{Array{Int64,2},1}:
 [1 1]
 [1 1]

In [9]:
fill!(a, [1 1])  # size和型別都跟a一樣

2-element Array{Any,1}:
 [1 1]
 [1 1]

In [15]:
fill([1 1], size(b))  # size跟b一樣，但型別從Int64改變成Array{Int64,2}

2-element Array{Array{Int64,2},1}:
 [1 1]
 [1 1]

In [11]:
fill!(b, [1 1])  # 因為原本b的型別是Array{Int64,1}，所以要將[1 1]的型別從Array{Int64,2}轉型成Int64

MethodError: MethodError: Cannot `convert` an object of type Array{Int64,2} to an object of type Int64
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Ptr) where T<:Integer at pointer.jl:23
  ...

若要查看陣列的維度，可以使用 `ndims()` 函式回傳陣列的維度數。要注意的是，列陣列的維度也會是 2。

In [37]:
A = [1 5 3]

1×3 Array{Int64,2}:
 1  5  3

In [38]:
ndims(A)

2

行陣列 (或稱行向量) 的維度則會是 1。

In [39]:
a = [1, 5, 3]
ndims(a)

1

在創建行陣列 (或稱行向量) 時可以用**逗號**或**分號**換列或是**直接換列**已進行垂直方向的連接，但是在創建二維陣列 (矩陣) 時則不能用逗號換列，所以**建議可以統一用分號**，就不會混淆了。

In [49]:
# column array
A = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [17]:
# column array
A = [1.0; 3; 5; 0]

4-element Array{Float64,1}:
 1.0
 3.0
 5.0
 0.0

In [ ]:
# 2D array
A = [1 2; 3 4; 5 6]

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [29]:
# 2D array
A = [1 2
     3 4
     5 6]

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

用逗號則會產生錯誤。

In [28]:
A = [1 2, 3 4, 5 6]

LoadError: syntax: unexpected comma in matrix expression

但是用逗號可以連接物件(不同型別也可以)形成一個一維陣列(可以做到類似python的list的行為)

In [41]:
[[1 2], [3 4], [5 6]]

3-element Array{Array{Int64,2},1}:
 [1 2]
 [3 4]
 [5 6]

In [38]:
[[1; 2], [3 4], [5 6]]

3-element Array{Array{Int64,N} where N,1}:
 [1, 2]
 [3 4]
 [5 6]

In [32]:
[[1; 2.2], [3, 4], [5 6]]

3-element Array{Array,1}:
 [1.0, 2.2]
 [3, 4]
 [5 6]

In [60]:
A = [[1; 2.2], 3, 4, [5 6]]

4-element Array{Any,1}:
  [1.0, 2.2]
 3
 4
  [5 6]

In [61]:
push!(A, 5.0)

5-element Array{Any,1}:
  [1.0, 2.2]
 3
 4
  [5 6]
 5.0

In [62]:
push!(A, A[1:3])

6-element Array{Any,1}:
  [1.0, 2.2]
 3
 4
  [5 6]
 5.0
  Any[[1.0, 2.2], 3, 4]

In [63]:
[A, 3//14]

2-element Array{Any,1}:
   Any[[1.0, 2.2], 3, 4, [5 6], 5.0, Any[[1.0, 2.2], 3, 4]]
 3//14

In [64]:
append!(A, A[2:3])

8-element Array{Any,1}:
  [1.0, 2.2]
 3
 4
  [5 6]
 5.0
  Any[[1.0, 2.2], 3, 4]
 3
 4

In [35]:
# 分號會只能連接成二維陣列
[[1 2]; [3 4]; [5 6]]

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

建議水平連接使用空白，垂直連接使用分號會比較接近預期(接近matlab)

|Syntax|Function|Description|
|---|---|---
||cat|concatenate input arrays along dimension(s) k|
|[A; B; C; ...]|vcat|shorthand for `cat(A...; dims=1)|
|[A B C ...]|hcat|shorthand for `cat(A...; dims=2)|
|[A B; C D; ...]|hvcat|simultaneous vertical and horizontal concatenation|

In [50]:
# 2D array
A = [1:2 3:4]

2×2 Array{Int64,2}:
 1  3
 2  4

In [51]:
# column array
A = [1:2; 3:4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [56]:
# column array, but not what we expected
A = [1:2, 3:4]

2-element Array{UnitRange{Int64},1}:
 1:2
 3:4

### 向量 (Vector) 與矩陣 (Matrix)

如同一開始所提，向量和矩陣分別是一維和二維的陣列，在 Julia 中也提供了 `Vector` 和 `Matrix` 別名 (alias)。

In [58]:
Vector

Array{T,1} where T

In [59]:
Vector{Float64}(undef, 3)

3-element Array{Float64,1}:
 5.0e-324
 5.0e-324
 0.0

In [72]:
Vector{Union{Missing, Int}}(missing, 2)  # Element type T must be able to hold these values, i.e. Missing <: T.

2-element Array{Union{Missing, Int64},1}:
 missing
 missing

In [60]:
Matrix

Array{T,2} where T

In [62]:
Matrix{Float64}(undef, 2, 1)

2×1 Array{Float64,2}:
 1.93206189e-315
 1.69347988e-315

In [70]:
Matrix{Union{Nothing, Int}}(nothing, 2, 3)  # Element type T must be able to hold these values, i.e. Nothing <: T.

2×3 Array{Union{Nothing, Int64},2}:
 nothing  nothing  nothing
 nothing  nothing  nothing

### 指定陣列元素的型別

創建陣列時，可以讓 Julia 自動識別元素型別而不指定。要指定型別的話，在陣列前面加上型別即可。

In [73]:
Float32[1, 2, 3, 4]

4-element Array{Float32,1}:
 1.0
 2.0
 3.0
 4.0

如果指定的類型無法被精確轉型時 (例如欲將浮點轉為整數)，系統會拋出 error。

In [74]:
Int32[1.1 2 3]

InexactError: InexactError: Int32(1.1)

### 常用函式建立並初始化陣列中的元素

下列為常用的函式，可以用來建立陣列並初始化陣列中的元素。

|函式|描述|
|--|--|
|zeros()|陣列元素初始化為 0|
|ones()|陣列元素初始化為 1|
|trues()|陣列元素初始化為 true 的 BitArray 類型|
|falses()|陣列元素初始化為 false 的 BitArray 類型|
|rand()|產生元素為隨機介於 \[0, 1) 區間的均勻分布數字|
|randn()|產生元素為隨機常態分布的數字|

In [75]:
zeros((2,3))

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [76]:
ones((2,3))

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [77]:
trues((2,3))

2×3 BitArray{2}:
 1  1  1
 1  1  1

In [78]:
falses((2,3))

2×3 BitArray{2}:
 0  0  0
 0  0  0

In [79]:
rand(Float32, 3, 2)

3×2 Array{Float32,2}:
 0.255338  0.105651
 0.831846  0.580452
 0.380902  0.535447

In [80]:
randn(3, 2)

3×2 Array{Float64,2}:
 -2.2943    -2.02489
 -0.621407  -1.37939
  1.20663   -0.615553

### 使用 `collect()` 函式建立陣列 

使用 `collect()` 函式來建立陣列。在下列範例中並搭配 `reshape()` 函式，改變陣列維度以建立多維陣列。

In [81]:
# 建立一維陣列，起始值為 1，數值間隔 2，結束值 10
collect(1:2:10)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [82]:
# 建立 5x2 陣列
reshape(collect(1:1:10), (5, 2))

5×2 Array{Int64,2}:
 1   6
 2   7
 3   8
 4   9
 5  10

## 2. 陣列的相關操作

### 索引

透過索引取得陣列元素值，有**線性索引**和**笛卡兒索引**兩種方式。

需特別留意的是，Julia 的索引值起始是 1 而非 0，和多數程式語言不同。

In [83]:
A = [1 2 3; 4 5 6; 7 8 9; 10 11 12]

4×3 Array{Int64,2}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

線性索引的順序如下，所以在下列範例中 A[7] 會得到 A[3, 2] 的值。

**Fortran style (column base)**

1->4->7->10->2->5->8->11->3->6->9->12

In [86]:
# 線性索引，得到 A[3, 2] 的值
A[7]

8

In [97]:
A[[3 1; 2 2]]

2×2 Array{Int64,2}:
 7  1
 4  4

In [99]:
A[1:2:5]

3-element Array{Int64,1}:
 1
 7
 2

笛卡兒索引是用 `A[<<row index>>, <<column index>>]` 的方式，取得該位置的值。

In [87]:
# 笛卡兒索引
A[3, 2]

8

`CartesianIndex` and arrays of `CartesianIndex` are not compatible with the `end` keyword to represent the last index of a dimension.

In [98]:
CartesianIndex(1,1)

CartesianIndex(1, 1)

In [92]:
A[[CartesianIndex(1,1),
   CartesianIndex(2,2),
   CartesianIndex(3,3)]]

BoundsError: BoundsError: attempt to access 4×3 Array{Int64,2} at index [CartesianIndex{2}[CartesianIndex(1, 1), CartesianIndex(2, 2), CartesianIndex(3, 12)]]

索引也可以使用範圍 (range) 來指定。

In [ ]:
A[1, 1:2]

2-element Array{Int64,1}:
 1
 2

`Colon()` (`:`), which represents all indices within an entire dimension or across the entire array

`Colon()` (`:`)代表在某一維度的所有索引值，或是遍歷整個陣列。

In [100]:
A[:, 1:2]

4×2 Array{Int64,2}:
  1   2
  4   5
  7   8
 10  11

In [101]:
A[:]

12-element Array{Int64,1}:
  1
  4
  7
 10
  2
  5
  8
 11
  3
  6
  9
 12

使用 `getindex()` 也可以取得該索引位置的值。

In [102]:
getindex(A, 3, 2)

8

**Logical indexing**

Often referred to as logical indexing or indexing with a logical mask, indexing by a boolean array selects elements at the indices where its values are `true`.

In [198]:
x = reshape(1:16, 4, 4)

4×4 reshape(::UnitRange{Int64}, 4, 4) with eltype Int64:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [199]:
x[[false, true, true, false], :]

2×4 Array{Int64,2}:
 2  6  10  14
 3  7  11  15

In [200]:
mask = map(ispow2, x)

4×4 Array{Bool,2}:
 1  0  0  0
 1  0  0  0
 0  0  0  0
 1  1  0  1

In [201]:
x[mask]

5-element Array{Int64,1}:
  1
  2
  4
  8
 16

###  遍歷 (Traversal)

In [120]:
# 使用笛卡兒索引將陣列中所有元素印出
A = [1 2 3; 4 5 6; 7 8 9; 10 11 12]

for i = 1:size(A, 1), j = 1:size(A, 2)
    print(A[i, j], " ")
end

1 2 3 4 5 6 7 8 9 10 11 12 

In [121]:
# 使用線性索引將陣列中所有元素印出
for i = 1:lastindex(A)
    print(A[i], " ")
end

1 4 7 10 2 5 8 11 3 6 9 12 

In [116]:
for i in eachindex(A)
    # Do something with i and/or A[i]
    print(A[i], " ")
end

1 4 7 10 2 5 8 11 3 6 9 12 

In [117]:
# 用迭代的方式將陣列中所有元素印出
# 也可以用 in 取代 ∈
for x ∈ A
    print(x, " ")
end

1 4 7 10 2 5 8 11 3 6 9 12 

In [128]:
A = rand(4,3);
B = view(A, 1:3, 2:3);
for i in eachindex(A)
   @show i
end

i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
i = 9
i = 10
i = 11
i = 12


### Comprehensions
Comprehensions provide a general and powerful way to construct arrays. Comprehension syntax is similar to set construction notation in mathematics:

```
A = [ F(x,y,...) for x=rx, y=ry, ... ]
```

In [204]:
x = rand(8)

8-element Array{Float64,1}:
 0.7262304398051549
 0.566920001776319
 0.745612999477189
 0.6183693240466859
 0.7018439575172712
 0.3646906231814264
 0.19458030132253534
 0.24205229893650793

In [205]:
[0.25*x[i-1] + 0.5*x[i] + 0.25*x[i+1] for i=2:length(x)-1]

6-element Array{Float64,1}:
 0.6514208607087455
 0.6691288311943457
 0.671048901271958
 0.5966869655656637
 0.40645137630066486
 0.24897588119075126

### Generator Expressions
Comprehensions can also be written without the enclosing square brackets, producing an object known as a generator. This object can be iterated to produce values on demand, instead of allocating an array and storing them in advance (see Iteration). For example, the following expression sums a series without allocating memory:

生成器可以被迭代，並於迭代時在後台生成數值，而不是預先分配陣列並儲存。

In [206]:
sum(1/n^2 for n=1:1000)

1.6439345666815615

When writing a generator expression with multiple dimensions inside an argument list, parentheses are needed to separate the generator from subsequent arguments:

在多個維度且在引數列表中時，需要用括號分開generator expression和其他引數

In [207]:
map(tuple, 1/(i+j) for i=1:2, j=1:2, [1:4;])

LoadError: syntax: invalid iteration specification

In [208]:
map(tuple, (1/(i+j) for i=1:2, j=1:2), [1:4;])

4-element Array{Tuple{Float64,Int64},1}:
 (0.5, 1)
 (0.3333333333333333, 2)
 (0.3333333333333333, 3)
 (0.25, 4)

Ranges in generators and comprehensions can depend on previous ranges by writing multiple for keywords:

可以使用先前區間的數值

In [209]:
[(i,j) for i=1:3 for j=1:i]

6-element Array{Tuple{Int64,Int64},1}:
 (1, 1)
 (2, 1)
 (2, 2)
 (3, 1)
 (3, 2)
 (3, 3)

In such cases, the result is always 1-d.

Generated values can be filtered using the `if` keyword:

In [210]:
[(i,j) for i=1:3 for j=1:i if i+j == 4]

2-element Array{Tuple{Int64,Int64},1}:
 (2, 2)
 (3, 1)

### 加入或剔除陣列的元素 (Push & Pop)

要加入或加入或剔除陣列的元素，可以透過下列函式：

|函式|說明|
|---|---|
|push!()|加入元素到陣列的尾端|
|pushfirst!()|加入元素到陣列成為第一個元素|
|pop!()|將陣列的最後一個元素剔除|
|popfirst!()|將陣列的第一個元素剔除|

以上函式都會直接變更原陣列。

In [106]:
A = collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [107]:
push!(A, 6)

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [108]:
pushfirst!(A, 0)

7-element Array{Int64,1}:
 0
 1
 2
 3
 4
 5
 6

In [109]:
pop!(A)
A

6-element Array{Int64,1}:
 0
 1
 2
 3
 4
 5

In [110]:
popfirst!(A)
A

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

### 陣列的組合

若陣列中含有陣列 (或稱巢狀陣列)，Julia 會自動依維度展開且自動轉換型別(promotion)。

In [111]:
[1 2 [3 4]]

1×4 Array{Int64,2}:
 1  2  3  4

In [112]:
[1 2 [3 4.1]]

1×4 Array{Float64,2}:
 1.0  2.0  3.0  4.1

巢狀內外陣列維度不相同會產生 error。

In [118]:
[1; 2 [3; 4]]

DimensionMismatch: DimensionMismatch("mismatch in dimension 1 (expected 1 got 2)")

陣列組合的背後，其實是呼叫了 `cat()`、`vcat()`、`hcat()`、或 `hvcat()` 函式。使用範例如下：

In [129]:
W = [1 2]
X = [3 4]
Z = [5 6]

# 合併陣列為列向量
cat(W, X, Z, dims=2)

1×6 Array{Int64,2}:
 1  2  3  4  5  6

In [130]:
W = [1 2]
X = [3 4]
Z = [5 6]

# 依"行"合併陣列
# 此範例合併陣列為列向量
hcat(W, X, Z)

1×6 Array{Int64,2}:
 1  2  3  4  5  6

In [131]:
# 依"列"合併陣列
# 等同於cat(W, X, Z, dims=1)
vcat(W, X, Z)

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [132]:
# 依照指定每列的行數合併數值成為陣列
D = hvcat((3, 3), 1, 2, 3, 4, 5, 6)

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [133]:
# 依照指定每列的行數合併數值成為陣列
D = hvcat((2, 2, 2), 1, 2, 3, 4, 5, 6)

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

### 切片(Slicing)和視圖(View)

#### 切片

陣列切片，也就是將陣列中的子陣列擷取出來；使用 `view()` 函式可以產生陣列的視圖，擷取出來的視圖，其型別為 `SubArray`。

在效能表現上，視圖會比切片快很多。

In [134]:
A = reshape(collect(1:15), 3, 5)

3×5 Array{Int64,2}:
 1  4  7  10  13
 2  5  8  11  14
 3  6  9  12  15

In [135]:
# 使用笛卡兒索引切片
A[1, 2]

4

In [136]:
# 使用範圍取得子陣列
A[2, 2:end]

4-element Array{Int64,1}:
  5
  8
 11
 14

使用條件式切片回傳的將會是一維陣列。

In [137]:
A[A .> 8]

7-element Array{Int64,1}:
  9
 10
 11
 12
 13
 14
 15

In [139]:
A[A > 8]  # 一定要加 .

MethodError: MethodError: no method matching isless(::Int64, ::Array{Int64,2})
Closest candidates are:
  isless(!Matched::Missing, ::Any) at missing.jl:87
  isless(::Real, !Matched::AbstractFloat) at operators.jl:157
  isless(::Real, !Matched::Real) at operators.jl:346
  ...

#### 視圖

In [140]:
b = view(A, 2:3, 2:3)

2×2 view(::Array{Int64,2}, 2:3, 2:3) with eltype Int64:
 5  8
 6  9

視圖也可以透過跟陣列一樣的方式進行操作，但是特別要留意的是，視圖中的元素值被改變時，原始陣列對應的元素值也會被改變。

In [141]:
b[1, 1] = 100

100

In [142]:
A

3×5 Array{Int64,2}:
 1    4  7  10  13
 2  100  8  11  14
 3    6  9  12  15

## 3. 點運算 (Vectorized Operation)

陣列對點運算的支援提供了很方便的機制，來進行對陣列中元素的處理和操作，而不需要再用遍歷的方式 (例如：迴圈) 來操作陣列。下面的範例是透過點運算，將陣列中的每個元素進行 `round()` (IEEE 754 捨入)、加法、及三次方的語法示範。

### 點運算適用的運算子 (operator)

||運算子|
|---|---|
|一元運算子|-, +|
|二元運算子|-, +, *, /, \\, ^|
|比較運算子|==, !=, ≈ (isapprox), ≉|

In [143]:
[1, 2, 3] .^ 3

3-element Array{Int64,1}:
  1
  8
 27

In [147]:
@. [1, 2, 3] ^ 3 * 2

3-element Array{Int64,1}:
  2
 16
 54

### Broadcasting

In [144]:
A = [1.1, 2.2, 3.5]
broadcast(+, A, 2)

3-element Array{Float64,1}:
 3.1
 4.2
 5.5

若不使用 broadcast 與加法的話，下列程式也可以得到相同的結果。

In [145]:
function f(x)
    x += 2
end

map(f, A)

3-element Array{Float64,1}:
 3.1
 4.2
 5.5

## 4. 排序 (Sort)

預設的 Sort 是 QuickSort，排序是以由小到大排序。

`sort()` 在排序後不會改變原來陣列的元素值順序，如果要改變的話，可以呼叫 `sort!()`。

In [152]:
A = [2, 1, 4, 3, 5]
sort(A)
print(A)

[2, 1, 4, 3, 5]

In [153]:
A = [2, 1, 4, 3, 5]
sort!(A)
print(A)

[1, 2, 3, 4, 5]

若要反序排序 (由大到小)，可以加上 `rev=true` 參數。

In [154]:
sort([2, 1, 4, 3, 5], rev=true)

5-element Array{Int64,1}:
 5
 4
 3
 2
 1

在排序時可以同時進行轉換，例如依據 `abs` 絕對值排序，不過如下面範例所示，`by` 並不會改變原本陣列的元素值，但是排序會依轉換後的值做排序。

如果陣列裡面的元素是其他集合型別，例如是 Tuple、Pair、Dictionary 的話，也可以用 `by` 來指定排序依據。在介紹到其他集合型別時會有更多範例說明。

In [155]:
sort([-2, 1, -4, 3, -5], by=abs, rev=true)

5-element Array{Int64,1}:
 -5
 -4
  3
 -2
  1

對於多維陣列，排序時必須指定 `dims` 參數，指定排序旳維度，否則會產生錯誤。

In [156]:
A = [2 1 3; 4 5 6; 1 3 5]

3×3 Array{Int64,2}:
 2  1  3
 4  5  6
 1  3  5

下例是指定依照列 (row) 值排序。

In [157]:
sort(A, dims=1)

3×3 Array{Int64,2}:
 1  1  3
 2  3  5
 4  5  6

In [158]:
sort([2, 1, 4, 3, 5], alg=InsertionSort)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

Julia 內建支援幾種不同的排序演算法：

- InsertionSort
- QuickSort
- PartialQuickSort(k)
- MergeSort

有關於 QuickSort 排序演算法的使用範例如下。首先我們先用 `rand()` 隨機產生 100 個 1 到 500 之間的數字。在範例中也運用 `@time` 巨集來輸出各種不同排序的執行時間進行比較。

對於各種不同排序的詳細說明及比較，請見參考資料：[[演算法] 排序演算法(Sort Algorithm)](http://notepad.yehyeh.net/Content/Algorithm/Sort/Sort.php)

In [170]:
x = rand(1:100, 10)

10-element Array{Int64,1}:
 26
 66
 74
 12
 10
 59
 21
 34
 36
 10

In [171]:
@time s = sort(x; alg=QuickSort)

  0.006446 seconds (25.04 k allocations: 1.366 MiB)


10-element Array{Int64,1}:
 10
 10
 12
 21
 26
 34
 36
 59
 66
 74

## 5. 搜尋 (Search)

搜尋某值是否存在於陣列中，可以用 `in`，回傳值為 true 或 false。

In [172]:
in(3, [1, 3, 5, 7, 9])

true

In [181]:
3 in [1, 3, 5, 7, 9]

true

使用 `findall()` 函式，搜尋並回傳結果值的索引。

In [173]:
findall(in(1), [5, 3, 2, 1])

1-element Array{Int64,1}:
 4

使用 `findmax()` 及 `findmin()` 函式，回傳找到的最大值或最小值，及其索引值。

In [174]:
findmax([2, 3, 1, 5]) 

(5, 4)

In [175]:
findmin([2, 3, 1, 5]) 

(1, 3)

使用 `maximun()` 及 `minimun()` 函式，回傳找到的最大值或最小值。

In [177]:
maximum([2, 3, 1, 5])

5

In [178]:
minimum([2, 3, 1, 5])

1

若是陣列已排序，可以使用 `searchsorted()`, `searchsortedfirst()`, `searchsortedlast()`，取得該值的索引值。

特別注意的是 `searchsorted()` 回傳的是索引值範圍 (range)。

In [179]:
searchsorted([1, 2, 3, 5], 1)

1:1

In [180]:
searchsortedfirst([1, 2, 3, 1], 1)

1

In [ ]:
searchsortedlast([1, 2, 3, 1], 1)

1

若要判斷是否已排序，可以透過 `issorted()` 函式，`rev` 參數判斷是由小到大或是由大到小排序。

In [182]:
issorted([5, 3, 2, 1], rev=true)

true

## 6. 陣列常用函式範例

|函式|說明|
|---|---|
|eltype(A)|	陣列A中的元素類型。|
|length(A)|	陣列A中的元素總數，例如 3x2 的陣列其元素總數為 6。|
|ndims(A)	|陣列A的維度數，例如二維陣列維度數為2。|
|size(A)|	陣列A的維度，回傳值是 tuple 類型，例如 3x2 的陣列其回傳值為 (3, 2)。|
|eachindex(A)|	陣列A所有索引值。|
|lastindex(A)|	陣列A最後一個索引值。|
|axes(A)|	陣列A所有維度的有效索引值，回傳值是 tuple 類型。|
|strides(A)|	陣列A各維度在記憶體中的距離(元素數目) ，回傳值是 tuple 類型。|

In [183]:
A = [1 2; 3 4; 5 6]

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [184]:
eltype(A)

Int64

In [185]:
length(A)

6

In [186]:
ndims(A)

2

In [187]:
size(A)

(3, 2)

In [188]:
size(A, 2)

2

In [189]:
axes(A)

(Base.OneTo(3), Base.OneTo(2))

In [190]:
axes(A, 2)

Base.OneTo(2)

In [193]:
collect(axes(A, 1))

3-element Array{Int64,1}:
 1
 2
 3

In [194]:
eachindex(A)

Base.OneTo(6)

In [195]:
lastindex(A)

6

In [196]:
strides(A)

(1, 3)

In [197]:
stride(A, 2)

3

# References:
- Marathon example notebook
- [Multi-dimensional Arrays](https://docs.julialang.org/en/v1/manual/arrays/)
- [Core.Array](https://docs.julialang.org/en/v1/base/arrays/#Core.Array)