# Julia 函式 (Functions)

在官方文件裡裡面，對於函式的定義是：”函式是一個將數組 (tuple) 引數 (argument) 對照到回傳值的物件”(a function is an object that maps a tuple of argument values to a return value. )。也就是說，呼叫時是用數組的型態把引數傳遞給函式，函式內的運算結果再透過回傳值傳回。

我們可以透過函式的定義，將相同模式的動作或邏輯，抽象化提取出來成為可以重覆被呼叫使用的模塊。

## 1. 函式 (Functions) 的基本語法與呼叫

函式的宣告和呼叫，Julia 的函式宣告是以 function 保留字做為開頭，end 做為結尾。

In [2]:
# This function accepts two arguments x and y and returns the value of the `last expression evaluated`, which is x + y.
function f(x, y)
    x + y
end

f (generic function with 1 method)

In [3]:
f(2, 3)

5

**Assignment form**

There is a second, more terse syntax for defining a function in Julia. The traditional function declaration syntax demonstrated above is equivalent to the following compact "assignment form".

In the assignment form, the body of the function must be a single expression, although it can be a compound expression (see Compound Expressions).

可以使用更簡潔的語法來定義函式，以下緊湊的"指定形式"所定義的函式等同於上述所定義的函式，但是僅能將單一表達式 (expression) 指定給函式。

In [6]:
f(x, y) = x + y

f (generic function with 1 method)

In [7]:
f(2, 3)

5

Without parentheses, the expression f refers to the function object, and can be passed around like any value:

可將函式當做物件指定給另一物件。

In [10]:
g = f;
g(2, 3)

5

Unicode can also be used for function names

函式的名稱也可以使用 Unicode 字元。

∑ 字元的產生方式是：\sum[tab]

In [17]:
∑(x, y) = x + y

∑ (generic function with 1 method)

In [18]:
∑(2, 4)

6

函式內的表達式也可以用複合表達式 (Compound Expression) 模塊包住。

In [19]:
f2(x, y) = begin
    z = 1
    z += x + y
end

f2(2, 3)

6

In [21]:
f2(x, y) = (z = 1; z += x + y)

f2(2, 3)

6

In [22]:
f2(x, y) = (
    z = 1;
    z += x + y;
)

f2(2, 3)

6

函式使用 return 保留字傳回值。

In [23]:
function f(x, y)
    return x + y
end

f(5, 6)

11

函式的傳回值不一定需要用 return，回傳值會是最後一個表達式的結果。

In [24]:
function b(x, y)
    x + y
end

b(2, 3)

5

如果有 return 的話，就以 return 的表達式做為傳回值，而不是回傳最後一個表達式。

In [26]:
function c(x, y)
    return x * y  # end here
    println(x + y)
end

c(2, 3)

6

In [27]:
function hypot(x,y)
    x = abs(x)
    y = abs(y)
    if x > y
       r = y/x
       return x*sqrt(1+r*r)
    end
    if y == 0
       return zero(x)
    end
    r = x/y
    return y*sqrt(1+r*r)
end

hypot (generic function with 1 method)

In [28]:
hypot(3, 4)

5.0

**Multiple Return Values**

In Julia, one returns a tuple of values to simulate returning multiple values. However, tuples can be created and destructured without needing parentheses, thereby providing an illusion that multiple values are being returned, rather than a single tuple value.

回傳tuple模擬多個回傳值，而tuple可以不經由括號"()"來建構及解構，因此產生了多個值被回傳，而非單個tuple被回傳的假象。

函式可以有多個傳回值，回傳值以逗號分隔。

In [31]:
# multiple return values
function d(x,y)
    i = x * y
    j = x + y
    
    return i, j
end

d (generic function with 1 method)

In [33]:
r1, r2 = d(2, 3)  # return a tuple and then "destructuring" to r1, r2

(6, 5)

In [34]:
println("r1: ", r1)
println("r2: ", r2)

r1: 6
r2: 5


**Define input and output type**

函式的引數和回傳值均可指定資料型別。

使用 `::` 指定型別。

In [30]:
function e(x::Int64, y::Int64)::Float64
    x + y
end

typeof(e(2, 3))

Float64

**return nothing**

For functions that do not need to return a value (functions used only for some side effects), the Julia convention is to return the value `nothing`.

當函式不需要回傳值時，習慣回傳`nothing`。

In [36]:
function pow(x)
    x ^ 2
    return nothing
end

pow (generic function with 1 method)

In [37]:
pow(5)

也可以直接用return，後面不加其它語句。

In [38]:
function pow(x)
    x ^ 2
    return
end

pow (generic function with 1 method)

In [40]:
pow(3)

也可以在最後一行使用nothing

In [45]:
function pow(x)
    x ^ 2
    nothing
end

pow (generic function with 1 method)

In [46]:
pow(3)

**Optional Arguments**

函式的引數可設定預設值，有預設值的引數可視為選用 (optional) 的引數，在呼叫函式時不強制傳入。

In [47]:
function date(year::Int64, month::Int64=1, day::Int64=1)
    return year, month, day
end

println("傳入年月日: ", date(2019, 7, 1))
println("傳入年,使用預設的月日: ", date(2019))

傳入年月日: (2019, 7, 1)
傳入年,使用預設的月日: (2019, 1, 1)


**Keyword Arguments**

Functions with keyword arguments are defined using a semicolon in the signature.

In [67]:
function foo(x, y; base=ℯ, power::Int=2)
    return hypot(log(base, x), log(base, y)) ^ power
end

foo (generic function with 1 method)

In [68]:
foo(1000, 10000)

132.54745276196

呼叫函式時可以使用逗號或分號分隔Keyword Arguments和前面的引數，使用逗號的方式比較常見。

一定要使用分號分隔的情況僅有在
1. 傳遞varargs時
2. [Keyword Arguments](https://docs.julialang.org/en/v1/manual/functions/#Keyword-Arguments-1)頁面所述的，需要使用關鍵字時

更詳細的說明請參考[Keyword Arguments](https://docs.julialang.org/en/v1/manual/functions/#Keyword-Arguments-1)。

In [69]:
foo(1000, 10000, base=10, power=1)  # 使用逗號 ","

5.0

In [70]:
foo(1000, 10000; base=10, power=1)  # 使用分號 ";"

5.0

## 2. 匿名函式

函式可以是匿名的，也就是沒有給函式名稱。

In [71]:
# 匿名函式的寫法-1
x -> x * 2 * π

#8 (generic function with 1 method)

In [72]:
# 或是：匿名函式的寫法-2
function (x)
    x * 2 * π
end

#10 (generic function with 1 method)

可以把匿名函式當做引數傳入到另一個函式。

In [73]:
# 透過匿名函式，計算半徑為 2, 4, 6 的圓周
diameters = [2, 4, 6]
map(x -> x * 2 * π, diameters)

3-element Array{Float64,1}:
 12.566370614359172
 25.132741228718345
 37.69911184307752

## 3. 函式的點運算 (Dot Operation)

相似於運算子的點運算，同樣的在函式數也可以使用點運算。

以下範例將陣列做為引數傳入，透過函式的點運算，傳回陣列各元素的平方值。

In [76]:
A = [1.0, 2.0, 3.0]

function B(x)
    x ^= 2
end

B.(A)

3-element Array{Float64,1}:
 1.0
 4.0
 9.0

In [81]:
broadcast(B, A)

3-element Array{Float64,1}:
 1.0
 4.0
 9.0

In [78]:
@. B(A)

3-element Array{Float64,1}:
 1.0
 4.0
 9.0

Since adding dots to many operations and function calls in an expression can be tedious and lead to code that is difficult to read, the macro `@.` is provided to convert every function call, operation, and assignment in an expression into the "dotted" version.

In [91]:
Y = [1.0, 2.0, 3.0, 4.0];

X = similar(Y); # pre-allocate output array

# X .= ..., which is equivalent to broadcast!(identity, X, ...)  *broadcast! have in-place behavior
@. X = sin(cos(Y)) # equivalent to X .= sin.(cos.(Y))

4-element Array{Float64,1}:
  0.5143952585235492
 -0.4042391538522658
 -0.8360218615377305
 -0.6080830096407656

In [92]:
X

4-element Array{Float64,1}:
  0.5143952585235492
 -0.4042391538522658
 -0.8360218615377305
 -0.6080830096407656

In [93]:
X .= sin.(Y)  # equivalent to broadcast!(sin, X, Y)

4-element Array{Float64,1}:
  0.8414709848078965
  0.9092974268256817
  0.1411200080598672
 -0.7568024953079282

In [94]:
X

4-element Array{Float64,1}:
  0.8414709848078965
  0.9092974268256817
  0.1411200080598672
 -0.7568024953079282

In [90]:
[1:5;] .|> [x->x^2, inv, x->2*x, -, isodd]  # [1^2; inv(2), 2*3, -4, isodd(5)]

5-element Array{Real,1}:
    1
    0.5
    6
   -4
 true

In [101]:
[1^2; inv(2); 2*3; -4; isodd(5)]

5-element Array{Float64,1}:
  1.0
  0.5
  6.0
 -4.0
  1.0

## 4. 執行函式後引數值變更範例

- 另外這邊也示範了，同一行 Julia 程式可以撰寫多個 expression，各個 expression 間以 ";" 分隔。
- `sort()` 是 Julia 的內建函式

In [102]:
# 不變更 (non-modifying) 版本
v = [3, 1, 2]; sort(v)

3-element Array{Int64,1}:
 1
 2
 3

In [103]:
# v 的原始排序並未改變
v

3-element Array{Int64,1}:
 3
 1
 2

In [104]:
# 變更 (modifying) 版本，在執行完 sort!() 後 v 的順序也已改變
v = [3, 1, 2]; sort!(v); v

3-element Array{Int64,1}:
 1
 2
 3

In [105]:
v = [3, 1, 2]; sort!(v)

3-element Array{Int64,1}:
 1
 2
 3

## 5. 多重分派 (Multiple Dispatch)

有時候相同功能的函式，可能會需要處理不同型別的值，這時候我們可以透過多重分派 (或譯多態分發) 的方式，定義同名但是傳入或回傳不同型別。Julia 是動態程式語言，會在執行階段 (runtime) 進行判斷。

In [107]:
function h(x::Int64, y::Int64)::Int64
    println("Int64 版本")
    x + y
end

function h(x::Float64, y::Float64)::Float64
    println("Float64 版本")
    x + y
end

h (generic function with 2 methods)

In [108]:
h(2.0, 3.0)

Float64 版本


5.0

In [109]:
h(2, 3)

Int64 版本


5

## 6. 變數作用域 (Scope of Variable) 的示範

Scope of Variable 在不同的程式區塊裡面有不同的影響，在這邊以函式做為範例說明。有關於 Scope of Variable 的詳細說明，請參照官方文件 [Scope of Variables](https://docs.julialang.org/en/v1/manual/variables-and-scoping/index.html)，後續的內容也會在相關的章節中提供更多的範例。

In [110]:
# 宣告 global 變數 x 與 y
x, y = 1, 2

function baz()
    # 在函式內宣告一個新的 x，這裡的 x 是屬於 local 變數
    # 有沒有 local 保留字都可以
    local x = 2 
    
    function bar()
        x = 10       # 賦予 local x 新的值
    
        return x + y 
        # y 是 global 變數，此 return 值應為 10 + 2
        # 其中 10 是 local x 的新值 10
    end
    
    return bar() + x # 回傳 bar() 函式傳回值與 local x 相加的值，應為 12 + 10

end

println("baz(): ", baz())

println("global x = $x, y = $y") # global x 與 y 值仍不變

baz(): 22
global x = 1, y = 2


### global 保留字

如果我們要使用的是 global x 的話，在函式指定值時加上 global 保留字，例如下列程式第 6 行示範。

In [111]:
# 宣告 global 變數 x 與 y
x, y = 1, 2

function baz()
    # 加上 global 保留字，代表我們要使用的是 global x
    global x = 20 
    
    function bar()
        return x + y
        # x, y 均是 global 變數，此 return 值應為 20 + 2
    end
    
    return bar() + x # 回傳 bar() 函式傳回值與 local x 相加的值，應為 22 + 20

end

println("baz(): ", baz())

println("global x = $x, y = $y") # global x 已改變

baz(): 42
global x = 20, y = 2


# Function composition and piping
Functions in Julia can be combined by composing or piping (chaining) them together.
多個函式可以組合或是組成管道(鏈結)

Function composition is when you combine functions together and apply the resulting composition to arguments. You use the function composition operator (`∘`) to compose the functions, so `(f ∘ g)(args...)` is the same as `f(g(args...))`.

使用`∘` \circ[tab]組合函數，`(f ∘ g)(args...)`等同於`f(g(args...))`

In [112]:
?∘

"∘" can be typed by \circ<tab>

search: ∘



```
f ∘ g
```

Compose functions: i.e. `(f ∘ g)(args...)` means `f(g(args...))`. The `∘` symbol can be entered in the Julia REPL (and most editors, appropriately configured) by typing `\circ<tab>`.

Function composition also works in prefix form: `∘(f, g)` is the same as `f ∘ g`. The prefix form supports composition of multiple functions: `∘(f, g, h) = f ∘ g ∘ h` and splatting `∘(fs...)` for composing an iterable collection of functions.

!!! compat "Julia 1.4"
    Multiple function composition requires at least Julia 1.4.


# Examples

```jldoctest
julia> map(uppercase∘first, ["apple", "banana", "carrot"])
3-element Array{Char,1}:
 'A'
 'B'
 'C'

julia> fs = [
           x -> 2x
           x -> x/2
           x -> x-1
           x -> x+1
       ];

julia> ∘(fs...)(3)
3.0
```


In [114]:
map(first ∘ reverse ∘ uppercase, split("you can compose functions like this"))

6-element Array{Char,1}:
 'U'
 'N'
 'E'
 'S'
 'E'
 'S'

In [113]:
?|>

search: |>



```
|>(x, f)
```

Applies a function to the preceding argument. This allows for easy function chaining.

# Examples

```jldoctest
julia> [1:5;] |> x->x.^2 |> sum |> inv
0.01818181818181818
```


In [115]:
1:10 |> sum |> sqrt  # equivalent composition: (sqrt ∘ sum)(1:10)

7.416198487095663

The pipe operator can also be used with broadcasting, as .|>, to provide a useful combination of the chaining/piping and dot vectorization syntax.

管道運算子也可以使用廣播，`.|>`，提供piping和向量化語法的結合。

In [116]:
["a", "list", "of", "strings"] .|> [uppercase, reverse, titlecase, length]

4-element Array{Any,1}:
  "A"
  "tsil"
  "Of"
 7

# References:
- Marathon example notebook
- [Functions](https://docs.julialang.org/en/v1/manual/functions/)
- [Control Flow](https://docs.julialang.org/en/v1/manual/control-flow/)
- [Julia語言—從入門到專案系列 第 6 篇 [Day 06] Multiple dispatch](https://ithelp.ithome.com.tw/articles/10185416)
- [Essentials](https://docs.julialang.org/en/v1/base/base/)